# -*- coding: utf-8 -*-
"""
/***************************************************************************
 favLayer
                                 A QGIS plugin
 saves favorite layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-05-15
        git sha              : $Format:%H$
        copyright            : (C) 2019 by 2
        email                : 1
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fav_layer_dialog import favLayerDialog
import os.path
testDisplayList = [r"documents\parcel.shp", r"downloads\NLCD.tif"]
testHiddenList = [r"C:\Users\Mark\Documents\parcels.shp", r"C:\Users\Mark\downloads\NLCD.tif" ]
testFilePath = [r"C:\Users\Mark\downloads\NLCD.tif"]
class favLayer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'favLayer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&fav layer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('favLayer', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fav_layer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'fave layer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&fav layer'),
                action)
            self.iface.removeToolBarIcon(action)


########################################### All of out functions should be between these###################################
    def printsomething(self):
        print("test")

    def getFileLocation(self):  # Mark will do this function
        '''
        This function activates when the user presses the imnport button in the interface.
        It connects to the file path widget and captures the text inside as s tring that the user saves.
        The function should use a try clause in order to make sure the path is valid.
        Also check that the file selected is a data type that can be imported. (like a feature class or raster)
        Input:The text captured by the file widget.
        Output:The file location saved as a string.
        '''
        #Connect to file path widget
        #filepath =self.dlg.fileWidget()
        global filepath
        filepath = testFilePath
        self.addStringToDisplayedList()

    def addStringToDisplayedList(self):  # Jillian will do this function
        '''
        This function runs after getfilelocation.
        This function takes the file path string and clips it down to just the final folder and file name.
        It takes this string and saves it to the end of the displayed list and repoptutes the displayed list.
        Input:String with file path.
        Output:Updated displayed list.
        '''
        #use split to split string by / into a list, then get the last couple items that contain the file
        # name and last folder and join them and make sure the / is there and doubled if nessiary

    def addLocationToHiddenList(self):  # Jillian will do this function
        '''
        This function runs after the addstringtodisplayedlist.
        This function takes the file location and adds it to the hidden list.
        Read the hidden list, append the file name to the end of the hidden list.
        Input:The file location.
        Output:Updated hidden list in the UI.
        '''

    def addLayerToMap(self):  # Mark will do this function
        '''
        This function runs when the user presses the add to map button.
        This function captures the index in the displayed list that the user has selected,
        then uses the string attached to the hidden list with that index and loads the file for that given path.
        First, use a try clause to see if the user has selected something.
        If the user has selected something, return the index of the displayed list to an object.
        Use the index in the hidden list to capture the string for that file.
        Check the file extension.
        Use if statements to point to the correct way of loading that file type.
        Input:The index number captured from the user.
        Output:Loads the file into QGIS.
        '''

    def checkForLists(self):  # Christine will do this function
        '''
        This funtion should run when the plugin loads
        This function looks in the master path for lists (hidden and displayed) that were previously saved.
        If a list is missing, this function creates a new list of that type and saves it as a global variable.
        If the file is there, it saves it to a global variable.
        Then the function populates the list box with the displayed list.
        Input:Master path of lists.
        Output:Loading the displayed list into the UI.
        '''
        # should use os.exists i think

    def deleteFromLists(self):  # Christine will do this function
        '''
        This function activates when the user presses the "X" button.
        First, the function checks to see whether the user selected anything from the displayed list in a try clause.
        If the user did select soemthing, the index is saved as an object.
        The object at that index is then popped off the displayed and the hidden list.
        Then the displayed list is repopulated in the UI.
        Input:The index number captured from the user.
        Output:Displayed list with fewer items.
        '''

    #########################################################################################################################


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = favLayerDialog()
            #self.dlg.pushButton_2.clicked.connect(self.printsomething)

        # fetch currently loaded layers
        #self.dlg.comboBox.clear()
        # show the dialog
        self.dlg.show()
        self.dlg.addToListButton.clicked.connect(self.getFileLocation)

############################# All button, list connections() should be between theses ###################################
        layer_list = ["one","two","four"]
        # with open(
        #         "C:\\Users\\Mark\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\fav_layer\\text.txt",
        #         "r") as file:
        #     for lines in file:
        #         layer_list.append(lines)

        #self.dlg.comboBox.addItems(layer_list)


#######################################################################################################################

        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
